apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-nat-agent
  namespace: kube-nat
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: kube-nat
      component: agent
