---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nat-agent
  namespace: kube-nat
  annotations:
    eks.amazonaws.com/role-arn: ""   # set to your IRSA role ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nat-dashboard
  namespace: kube-nat
