---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nat-agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-nat.labels" . | nindent 4 }}
  {{- if .Values.agent.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.agent.irsaRoleArn | quote }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nat-dashboard
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-nat.labels" . | nindent 4 }}
